Slicegateway tunnel metrics
kubeslice/worker-operator pull request #230
Opened 2023-04-22 11:05 UTC by kmjayadeep

Added metrics for slicegateway tunnel status

![2023-04-22 13:02:42+02:00](https://user-images.githubusercontent.com/6793260/233780357-07505872-c725-42cc-ad1e-e4df92e40b12.png)

Also fixed label names in existing metrics

2023-04-24 07:18 UTC, rajendra-avesha requested changes

2023-04-24 07:18 UTC, rajendra-avesha commented on controllers/slicegateway/reconciler.go
> +	"github.com/kubeslice/kubeslice-monitoring/pkg/metrics"
FAIL! -- 26 Passed | 1 Failed | 1 Pending | 0 Skipped
IT is failing

2023-05-09 05:08 UTC, YachikaRalhan approved these changes

2023-05-25 19:37 UTC, kmjayadeep commented
closing in favor of https://github.com/kubeslice/gateway-sidecar/pull/32

2023-05-25 19:37 UTC, closed without merging