Feature e2e
kubeslice/worker-operator pull request #64
Opened 2022-07-01 15:34 UTC by saivenkatesh1909

The above changes will build worker-operator and will perform a e2e test on every pull request. currently this works on push, but we will modify the script to use the on push.

Also we need to the change the secret/personal access token and also the e2e repo to complete the function. Please verify

2022-07-11 08:17 UTC, kmjayadeep requested changes

2022-07-11 08:17 UTC, kmjayadeep commented on .github/workflows/scripts/kind-nodeip.sh
> +sed -i "s/<NEW_IP>/${HOST_IP}/g" .github/workflows/scripts/kind-controller.yaml
shouldn't you be using node ip of the kind cluster instead of host ip?

2022-07-11 08:17 UTC, kmjayadeep commented on .github/workflows/end-to-end-test.yaml
> +      run:  sh .github/workflows/scripts/kind-nodeip.sh
`determine node-ip` step should be after creating the kind clusters. It is not possible to get node ip before right?

2022-07-11 08:17 UTC, kmjayadeep commented on .github/workflows/end-to-end-test.yaml
> +      id: extract
`actions-docker-extract` is to extract files from an image. Here we need to do `docker run` with mounted volumes instead

2022-07-11 08:17 UTC, kmjayadeep commented on .github/workflows/end-to-end-test.yaml
> +      uses: actions/checkout@v3
No need to clone the repo and build it here. the docker image can be built in a separate pipeline for e2e repo and push to docker registry. We can just pull the image and use it

2022-07-11 08:17 UTC, kmjayadeep commented on .github/workflows/scripts/kind-worker-1.yaml
> +  apiServerAddress: "<NEW_IP>"
why do we need to expose it in the host ip address?

2022-07-24 15:43 UTC, saivenkatesh1909 reviewed
updated the changes with the new pull request

2022-07-25 08:03 UTC, kmjayadeep approved these changes

2022-07-25 08:53 UTC, merged